# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/annotations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from protobuf.options import auth_pb2 as protobuf_dot_options_dot_auth__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/annotations.proto',
  package='protobuf',
  syntax='proto3',
  serialized_options=b'Z:github.com/golang/protobuf/protoc-gen-go/protobuf;protobuf',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aprotobuf/annotations.proto\x12\x08protobuf\x1a google/protobuf/descriptor.proto\x1a\x1bprotobuf/options/auth.proto:J\n\x04\x61uth\x12\x1e.google.protobuf.MethodOptions\x18\xa0\xf0\x30 \x01(\x0b\x32\x1a.protobuf.options.AuthRule:1\n\x04text\x12!.google.protobuf.EnumValueOptions\x18\x84\xf1\x30 \x01(\tB<Z:github.com/golang/protobuf/protoc-gen-go/protobuf;protobufb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,protobuf_dot_options_dot_auth__pb2.DESCRIPTOR,])


AUTH_FIELD_NUMBER = 800800
auth = _descriptor.FieldDescriptor(
  name='auth', full_name='protobuf.auth', index=0,
  number=800800, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
TEXT_FIELD_NUMBER = 800900
text = _descriptor.FieldDescriptor(
  name='text', full_name='protobuf.text', index=1,
  number=800900, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)

DESCRIPTOR.extensions_by_name['auth'] = auth
DESCRIPTOR.extensions_by_name['text'] = text
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

auth.message_type = protobuf_dot_options_dot_auth__pb2._AUTHRULE
google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(auth)
google_dot_protobuf_dot_descriptor__pb2.EnumValueOptions.RegisterExtension(text)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
